### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lintool**
Reorganizing documentation - adding internal links.

### CODE REVIEW

**Comment by lintool** [comment]
+ Added internal links for easier navigation
+ Tweaked headings to make more descriptive

**Comment by lintool** [comment]
Also, "news" isn't so new anymore... ;)

**Comment by lintool** [comment]
hey @rodrigonogueira4 what do you think of moving the Anserini replication documentation over to the Anserini repo? (with proper links back, etc.)

I can think of two advantages:
+ to replicate, the person's going to have to learn Anserini anyway, so might as well point to over there.
+ we can start a replication log just with any other Anserini experiment... it's a big awkward to do here.

**Comment by rodrigonogueira4** [comment]
> hey @rodrigonogueira4 what do you think of moving the Anserini replication documentation over to the Anserini repo? (with proper links back, etc.)
> 
> I can think of two advantages:
> 
> * to replicate, the person's going to have to learn Anserini anyway, so might as well point to over there.
> * we can start a replication log just with any other Anserini experiment... it's a big awkward to do here.

I know that linked documentation is easier to maintain than multiple copies, but it is a big pain for the user to go back and forth between documentations.

**Review by rodrigonogueira4 — APPROVED** [review]
LGTM! Thanks for doing this!

**Pull request merged**
