### PR TITLE
Replicating MS MARCO doc ranking experiments

### PR DESCRIPTION
**Pull request by lintool**

### CODE REVIEW

**Comment by rodrigonogueira4** [comment]
Please let me know when it is ready for review.

**Comment by lintool** [comment]
Yup! Lots of minor tweaks to smooth out replication!

**Comment by lintool** [comment]
@rodrigonogueira4 ready for review!

I've successfully replicated all three conditions: passage expansion, per-doc doc expansion, and per-segment doc expansion.

**Review by rodrigonogueira4 — APPROVED** [review]
Thanks for improving this documentation!

**Pull request merged**
